language: java
jdk:
  - oraclejdk8
script: mvn clean install
notifications:
  email:
    recipients:
      - animachandran@gmail.com
      - meeualias98@gmail.com
    on_success: always
    on_failure: always 
